# Generated by Django 3.1.6 on 2021-02-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210203_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='SOME STRING', max_length=200, unique=True),
        ),
    ]
